@echo off
echo Temporarily disabling strict SSL for npm...
call npm config set strict-ssl false
echo.
echo Temporarily disabling TLS unauthorized rejections for Node.js...
set NODE_TLS_REJECT_UNAUTHORIZED=0
echo.
echo Deleting corrupted Electron module...
rmdir /s /q node_modules\electron
echo.
echo Reinstalling Electron module...
echo.
echo Running npm install to check and restore other dependencies...
call npm install
echo.
echo Re-enabling strict SSL for npm...
call npm config set strict-ssl true
echo.
echo Unsetting NODE_TLS_REJECT_UNAUTHORIZED...
set NODE_TLS_REJECT_UNAUTHORIZED=
echo.
echo Recovery process complete.
pause
